kind: pipeline
name: default

trigger:
  branch:
    - version2
  event:
    - push

steps:
  - name: web-app
    image: node
    environment:
      NODE_PATH: ./src
    commands:
      - cd packages/adapter-web-app
      - yarn install
      - yarn build
      - cd build
      - git init
  - name: git_push
    image: appleboy/drone-git-push
    settings:
      branch: master
      remote: git@github.com:assistant-os/assistant-os.github.io.git
      force: true
      commit: true
      path: packages/adapter-web-app/build
    environment:
      GIT_PUSH_SSH_KEY:
        from_secret: GIT_PUSH_SSH_KEY
