kind: pipeline
name: default

trigger:
  branch:
    - version2
  event:
    - push

steps:
  - name: web-app
    image: node
    environment:
      NODE_PATH: ./src
    commands:
      - cd nodes/adapters/web-app
      - yarn install
      - yarn build
      - ls -a
      - pwd
      - cd .drone
      - ls
      - chmod 700 .drone/deploy.sh
      - .drone/deploy.sh
