version: '3.2'
services:
  assistant-os:
    image: assistant-os:latest
    build: .
    restart: always
    environment:
      - ADAPTER_HTTP_SECRET
      - ADAPTER_HTTP_PORT
      - ADAPTER_SLACK_TOKEN
      - ADAPTER_SLACK_CHANNEL
      - ADAPTER_SLACK_SIGNING_SECRET
      - ADAPTER_SLACK_PORT
      - THEMOVIEDB_API_KEY
      - NAME
      - HAVE_I_BEEN_PWNED_API_KEY
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - '$PWD/data:/home/node/app/data'
    labels:
      - traefik.enable=true
      - 'traefik.frontend.rule=Host:${HOST}'
      - traefik.backend=assistant-os
      - traefik.port=8080
      - traefik.frontend.entryPoints=https
    networks:
      - proxy
networks:
  proxy:
    external: true
