version: '3.2'
services:
  assistant-os:
    image: techmindio/assistant-os
    restart: always
    environment:
      - PORT=8080
      - HOST=127.0.0.1 # all nodes are in the same host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - '$PWD/data:/data'
      - '$PWD/logs:/logs'
    labels:
      - traefik.enable=true
      # - traefik.frontend.rule=Host:<host>
      - traefik.backend=assistant-os
      - traefik.port=8080
      - traefik.frontend.entryPoints=https
    networks:
      - proxy
networks:
  proxy:
    external: true
