version: '3.2'
services:
  assistant-os:
    build: .
    restart: always
    environment:
      - THEMOVIEDB_API_KEY
      - TOKEN
      - HOST
      - PORT
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - '$PWD/data:/home/node/app/data'
      - '$PWD/logs:/home/node/app/logs'
    labels:
      - traefik.enable=true
      - 'traefik.frontend.rule=Host:${HOST}'
      - traefik.backend=assistant-os
      - traefik.port=8080
      - traefik.frontend.entryPoints=https
    networks:
      - proxy
networks:
  proxy:
    external: true
