version: '3.2'
services:
  assistant-os:
    image: assistant-os:latest
    build: .
    restart: always
    environment:
      - HTTP_ADAPTER_SECRET
      - HTTP_ADAPTER_PORT
      - THEMOVIEDB_API_KEY
      - NAME
      - SLACK_TOKEN
      -
      - TOKEN
      - HOST
      - PORT
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - '$PWD/data:/home/node/app/data'
    labels:
      - traefik.enable=true
      - 'traefik.frontend.rule=Host:${HOST}'
      - traefik.backend=assistant-os
      - traefik.port=8080
      - traefik.frontend.entryPoints=https
    networks:
      - proxy
networks:
  proxy:
    external: true
